### ISSUE TITLE
无法远程连接

### ISSUE THREAD

**Issue by huo-feng-ding** [debuggap/vide-plugin-debug-webview#1]
PC我使用的是windows操作系统,要调试的页面是远程的iPhone下的app里的webview; 按文档https://www.debuggap.com/zh-cn/debug_webview.html 里的试了,连接不上去,PC上的console就显示一行new client comes

**Comment by vicwang163** [comment]
不好意思，迟回，你可以加我微信870630302，具体帮你看看

**Comment by vicwang163** [comment]
BTW，可能公司网络的一些限制，手机跟pc链接可能会不通，首先确保直接可以互相联调的就行

**Comment by huo-feng-ding** [comment]
我电脑是windows操作系统,iPhone手机是用PC上的wifi热点来连的网, 在iPhone里的webview里将那个js脚本引入, 按文档操作进行连接, 一直连不上去.    我换成angular手机做同样的操作是可以连上去的

**Comment by vicwang163** [comment]
@MaxSherry 对于你的问题，你试试看其他iphone手机是否可以，或者你清空那台iphone的localStorage试试看
